version: '3'
services:
  web:
    build: .
    ports:
    - "8080:8080"
    volumes:
      - ./static:/go/src/temp/static
      - ./templates:/go/src/temp/templates
    command: bash -c 'cd /go/src/temp && go run main.go'
    



